wspurgin/rspec-sidekiq

- lib/rspec/sidekiq/batch.rb
We use matchers extensively, but `RSpec::Sidekiq::NullBatch` is problematic because we can't set expectations on batches. (Letting batches persist in test mode through https://github.com/guilleiguaran/fakeredis works well enough). This is just adding a flag to conditionally disable `NullBatch`.
If you have any ideas how to test this I'm all ears.
> Add flag to skip Batch stubs

- README.md
- lib/rspec/sidekiq/matchers/be_delayed.rb
to make it easier to test that a Rails Mailer mail got delayed
I'm not sure how to write a spec for this without adding ActiveMailer as a dependency?
> allow passing an instance method to be_delayed matcher

- lib/rspec/sidekiq/batch.rb
Absent this change, #on_complete and #on_success callbacks will not be run under test.
See https://github.com/mperham/sidekiq/wiki/Batches#callbacks
> Add support for NullBatch#on and NullStatus#failures to the null batch objects.

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
I discovered recently that the have_enqueued_job matcher breaks when one of the job arguments is a hash (unless they all are). I think this has to do with the `any?` test in `map_arguments`.
I am opening a PR with the failing test, but hopefully I’ll have a complete patch shortly after lunch.
> Matchers::HaveEnqueuedJob breaks on jobs with Hash arguments

- .travis.yml
- CHANGES.md
- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- rspec-sidekiq.gemspec
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
This PR fix clash with rspec-rails
> Fix clash with rspec-rails

- lib/rspec/sidekiq/matchers/be_unique.rb
- spec/rspec/sidekiq/matchers/be_unique_spec.rb
Sidekiq Enterprise uses the `unique_for` option, not `unique`.
This PR will detect which Gem a user is using for the `be_unique` matcher.
It also adds a `for` matcher so you can specify the interval.
> Add support for Sidekiq Enterprise

- rspec-sidekiq.gemspec
- this way users of rspec-sidekiq can properly upgrade their version of rspec/rspec-rails depending on which "meta gem" they use.
PR for #94 
I removed the rspec-rails dependency (As it is not needed) instead specs should be written around that feature and travis CI's gemfile matrix should be used to test with and without rspec-rails.
> only depend on rspec-core

- .travis.yml
- rspec-sidekiq.gemspec
Without this, we don't load rspec-mocks or rspec-expectations which
means none of the tests can run. Previously this worked because fuubar
required the full rspec library, but as of 2.2 it only requires
rspec-core.
https://github.com/thekompanee/fuubar/commit/a6b65681ee3a91033f7710287a20c63c5a903d07
This only adds a development dependency, so it won't undo the work in #96
> Rely on all of RSpec in development

- lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb
- spec/rspec/sidekiq/helpers/retries_exhausted_spec.rb
Currently this method doesn't allow for sending an exception, but
sidekiq will send it along with the block.
https://github.com/mperham/sidekiq/blob/35a7962093040784b48498e012bdff380ef991a8/lib/sidekiq/middleware/server/retry_jobs.rb#L143
> Pass exception to within_sidekiq_retries_exhausted_block

- README.md
- lib/rspec/sidekiq/batch.rb
- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- spec/rspec/sidekiq/batch_spec.rb
- spec/rspec/sidekiq/matchers/be_unique_spec.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
Allow you to test scheduled jobs chaining `#at` to `#have_enqueued_job`.
```ruby
Awesomejob.perform_at 5.minutes, 'Awesome', true
expect(AwesomeJob).to have_enqueued_job('Awesome', true).at(5.minutes)
```
I don't know if this is the best approach, but it's a start.
Suggestions are welcome.
> Add support for testing scheduled jobs

- lib/rspec/sidekiq/batch.rb
- spec/rspec/sidekiq/batch_spec.rb
- this prevents an ArgumentError when NullStatus#new is called in lib/rspec/sidekiq/batch.rb:71
> Use default arguments for NullStatus initialization

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
Version 3.0.0 included #109 which added the private `unwrapped_job_options` method:
```ruby
def unwrapped_job_options(jobs)
jobs = jobs.values if jobs.is_a?(Hash)
jobs.flatten.map do |job|
job.slice('at')
end
end
```
The method relies on `Hash#slice`, which is in ActiveSupport but not Ruby. This broke one of my gem's test suites because the `activesupport` gem isn't declared as a runtime dependency, only a development dependency, causing a `NoMethodError`:
```
Failure/Error: expect(FooJob).to have_enqueued_job(1)
NoMethodError:
undefined method `slice' for #<Hash:0x000000027b2df0>
```
I would actually like to avoid _any_ runtime gem dependencies on ActiveSupport or other Rails libraries, since Sidekiq itself does not require Rails.
In addition to the use of `slice`, `present?` was also …
> Avoid methods from ActiveSupport, which is not required at runtime

- README.md
We currently recommend have_enqueued_sidekiq_job, so we should use that
in the examples. Mentions the old syntax once just to note that it's
there and deprecated.
Closes #121
> Update README for matcher deprecation

- .travis.yml
- lib/rspec/sidekiq/matchers/be_retryable.rb
- lib/rspec/sidekiq/matchers/save_backtrace.rb
Changes to support ruby 2.4
* Test against 2.4 and not 2.1
* Use `Numeric` instead of `Fixnum`
> Ruby 2.4 Support

- README.md
#95 introduced a change which allows to use rspec-sidekiq alongside rspec-rails.  This PR adds a note to the README.md regarding this.
> Add a note about have_enqueued_job and rspec-rails to README.md

- .travis.yml
- gemfiles/sidekiq4.gemfile
- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- rspec-sidekiq.gemspec
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
- spec/spec_helper.rb
* Turn on BeDelayed with Sidekiq versions >= 5
* Test against old versions of Sidekiq
* Fix deprecation warning to only show on calling deprecated method(s)
> Fix tests and deprecations with Sidekiq 5

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
This makes sure that an extra level of array wrapping isn't added for tests which use the now-deprecated have_enqueued_job, which causes test failures.
> Re-splat arguments for the have_enqueued_job alias

- lib/rspec/sidekiq/batch.rb
Enables `sidekiq_batch#description=`
```ruby
batch = Sidekiq::Batch.new
batch.description = "Batch description (this is optional)"
batch.on(:success, MyCallback, :to => user.email)
batch.jobs do
rows.each { |row| RowWorker.perform_async(row) }
end
```
Reference: https://github.com/mperham/sidekiq/wiki/Batches
> Add description attr_accessor to NullBatch

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
I kept having issues where (only on my CI), the `have_enqueued_sidekiq_job(..).at(...)` matcher would fail, because the timestamps didn't match. I discovered it was due to sub-second differences. By comparing all times with `.to_i` it fixes it.
I noticed there were already two pull requests open regarding this -- I agree with the implementation in #150, but it has merge conflicts, so I've posted this PR in case it is useful to be merge-ready.
> Always convert time .to_i before comparing delayed jobs

- lib/rspec/sidekiq/batch.rb
- spec/rspec/sidekiq/batch_spec.rb
Sidekiq Pro batch callback feature supports the `Class#method` notation when registering a callback. It's documented [here](https://github.com/mperham/sidekiq/wiki/Batches#callbacks).
This commit adds support for it in `NullBatch`.
> Support Class#method notation in batch callback

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
- spec/spec_helper.rb
First reported in #183 and solution from #182
Closes #183 
Additional freebies in this PR:
- Simplify the Job options matcher to just expect `at` since that's what will be on the Sidekiq Job. We move the parsing/handling of expected values for `at` versus `in` to the methods in `HaveEnqueuedJob`
- Also updates the description on mismatch to show an "at" expectation when using `in` as the actual Sidekiq job will show "at" on a mismatch (see below)
The one downside of the failure message is that Sidekiq stores a `float` for the `at` option, and it might cause confusion when you first see the actual vs expected (your eye first goes to the missing `.0`. We purposefully coerce to integers to avoid fractional second drift when comparing.
> Correct evaluation for "in" option

- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
Should help in issues like #162 and #168 where the previous description made it harder to tell that the actual was an array of _jobs_ with arguments, not a single job with a single array arg.
New description would look like:
```ruby
SomeJob.perform_async "some_arg", "some_other_arg"
expect(SomeJob).to have_enqueued_sidekiq_job(["some_arg", "some_other_arg"])
#=> fails with message:
#
```
Closes #162
Closes #168
Also, it nests the "context" under each Job as well (formerly was "options" in the failure message - it's called the job hash "context" in Sidekiq, so I'm updating to use that terminology to be consistent).
The previous failure message only ever showed `"at"`, but I've elected to include the full job context without args in the output. I'm doing that to pave the way for a general …
> Update failure message to list out actual jobs line-by-line

- README.md
- lib/rspec/sidekiq/matchers/have_enqueued_job.rb
- rspec-sidekiq.gemspec
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
> Add `#on` matcher

- lib/rspec/sidekiq/matchers/be_delayed.rb
`be_delayed` has it's own version of the the interval calculation. It was still doing basic `at.to_i + interval` which can cause false positives (as we saw [tw](https://github.com/wspurgin/rspec-sidekiq/actions/runs/5726557567/job/15517242650)i[ce](https://github.com/wspurgin/rspec-sidekiq/actions/runs/5726557567/attempts/1) on main in recent builds)
> :bug: Fix be_delayed interval calculation

- README.md
- lib/rspec/sidekiq/matchers.rb
- lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_job_spec.rb
`have_enqueued_job` has been deprecated for a long while now. This finally removes it entirely.
> Remove have_enqueued_job and rename files/class

- README.md
- lib/rspec/sidekiq/matchers.rb
- lib/rspec/sidekiq/matchers/be_delayed.rb
- lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb
- rspec-sidekiq.gemspec
- spec/rspec/sidekiq/matchers/be_delayed_spec.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
Closes #144
Fixes a long standing bug where the order of args didn't matter.
Additionally, because we're now leveraging the ArgumentListMatcher we're actually able to supprot the ArgumentMatchers from `rspec-mocks`!
> Use ArgumentListMatcher to ensure order and allow use of richer builtin Argument matchers

- lib/rspec-sidekiq.rb
Sidekiq v6 does not load forwardable by `require 'sidekiq'; require 'sidekiq/testing'`
Therefore, depending on the library situation used, a `NameError` will be raised.
```
$ BUNDLE_GEMFILE=gemfiles/sidekiq6_5_rails7.gemfile bundle exec ruby -I lib -r rspec-sidekiq -e 1
/rspec-sidekiq/lib/rspec/sidekiq/matchers/base.rb:85:in `<class:EnqueuedJob>': uninitialized constant RSpec::Sidekiq::Matchers::EnqueuedJob::Forwardable (NameError)
extend Forwardable
^^^^^^^^^^^
```
Explicitly loading forwardable solves the problem.
> Load forwardable expressly

- rspec-sidekiq.gemspec
With the recent constraint of dropping support for Ruby 2.6 (which also includes JRuby 9.3), the minimum ruby version should be constrained in the gemspec so that it cannot be resolved for older versions.
In addition I would recommend re-releasing `4.0.0, 4.0.1, 4.0.2` gems so that `3.1.0` would be pulled in correctly.
> added required_ruby_version >= 2.7 into gemspec

- README.md
- lib/rspec/sidekiq/matchers/base.rb
- lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/enqueue_sidekiq_job_spec.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
There is currently no way to check whether a job was scheduled for some point in the future, or enqueued immediately.
Specifically, we can't use `have_enqueued_sidekiq_job.at( ... )` if a job was enqueued immediately.
This is because when Sidekiq doesn't add a `"at"` option when the date was in the past, which rspec-sidekiq currently relies on:
https://github.com/sidekiq/sidekiq/blob/bd1ca2b94ad73abdfd4347c83be527bb3ff60acb/lib/sidekiq/job.rb#L328C1-L329
This PR enables this:
```ruby
MyJob.perform_at(5.seconds.ago, "hello")
expect(MyJob).to have_enqueued_sidekiq_job("hello").immediately # passes
```
> Add "immediately" matcher

- .github/workflows/main.yml
Ruby 2.7 reach EOL in November. While the latest versions officially still support Ruby 2.7, the next release of rspec-sidekiq will drop support for Ruby 2.7
> Drop CI for Ruby 2.7 (EOL)

- lib/rspec/sidekiq/matchers.rb
Rails autoloading was probably saving most of us, but an explicit require for Composable is best.
> Fix: require matchers explicitly

- CHANGES.md
- lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
Deprecate `have_enqueued_sidekiq_job` with no arguments to release a new version in preparation for #215
> Deprecate `have_enqueued_sidekiq_job` with no arguments

- CHANGES.md
- README.md
- lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
First of all, thanks for your work on `rspec-sidekiq`, it helped cleaning up our tests tremendously!
---
When I started using `rspec-sidekiq`, I assumed it would work similarly to the builtin matchers.
For example, the negation of `raise_error` works as follows:
```ruby
expect { raise StandardError.new("arg") }.not_to raise_error(StandardError, 'arg') # expects StandardError with "arg"
expect { raise StandardError.new("arg") }.not_to raise_error(StandardError) # expects `StandardError`
expect { raise StandardError.new("arg") }.not_to raise_error # expects any exception
```
In the case of `rspec-sidekiq`, it's different:
```ruby
expect(AwesomeJob).not_to have_enqueued_sidekiq_job # expects no jobs with no args (instead of any job)
expect(AwesomeJob).not_to have_enqueued_sidekiq_job("arg") …
```
> Support `have_enqueued_sidekiq_job` with no args

- CHANGES.md
- README.md
- lib/rspec/sidekiq/matchers/base.rb
- lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb
- lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/enqueue_sidekiq_job_spec.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
Add support for expected number of jobs to both `enqueue_sidekiq_job` and `have_enqueued_sidekiq_job`. Plus fixes the copy in some error messages.
See the updated README and the specs for details.
Happy to make edits if needed 🙂
> Support expected counts

- .github/workflows/main.yml
- CHANGES.md
- lib/rspec/sidekiq/version.rb
🧹 just some house keeping before releasing 5.0 with the (albeit small) breaking change of behavior to `have_enqueued_sidekiq_job()`
> Prep for 5.0 release

- rspec-sidekiq.gemspec
Supported here: https://guides.rubygems.org/specification-reference/#metadata 
Useful for running https://github.com/MaximeD/gem_updater
> Add changelog_uri to gemspec

- CHANGES.md
- lib/rspec/sidekiq/matchers/base.rb
- Resolves https://github.com/wspurgin/rspec-sidekiq/issues/226
How about changing the code to one that doesn't use pattern-matching? I don't think the benefit from this pattern-matching was that great, and if this level of change will help Ruby 2.7 users, I consider this an acceptable change.
> Fix pattern matching warnings on Ruby 2.7

- .github/workflows/main.yml
- gemfiles/sidekiq8_rails8.gemfile
- lib/rspec/sidekiq/configuration.rb
- lib/rspec/sidekiq/matchers/base.rb
- rspec-sidekiq.gemspec
- spec/spec_helper.rb
- Fixed CI failing with
```
An error occurred in a `before(:suite)` hook.
Failure/Error: ActiveJob::Base.queue_adapter = :sidekiq
NameError:
uninitialized constant Sidekiq::ActiveJob
```
by requiring `sidekiq/rails` and added `railties` as dev dependency
- Added new gemfile for Sidekiq 8 & Rails 8
- Added support for Sidekiq 8 (https://github.com/sidekiq/sidekiq/blob/main/Changes.md#800)
> Support for Sidekiq 8

- lib/rspec/sidekiq/matchers/be_unique.rb
- spec/rspec/sidekiq/matchers/be_unique_spec.rb
In Sidekiq Enterprise's [Unique Jobs](https://github.com/mperham/sidekiq/wiki/Ent-Unique-Jobs#unlock-policy) feature, you have the ability to specify an unlock policy.
This PR adds an until matcher so that you may specify an expectation against a worker for it like so:
```ruby
describe MuhWorker do
it { should be_unique.until(:success) }
end
```
It also will fail that it is not supported if a user tries to use it with SidekiqUniqueJobs.
(all credit to @leviwilson for his work on this, I just rebased and brought it current)
> Sidekiq Enterprise: until matcher

- .github/workflows/main.yml
- README.md
`spec` is unnecessary.
```
~/ydah/rspec-sidekiq remove-example
❯ bundle exec rspec spec
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/wspurgin/rspec-sidekiq/wiki/FAQ-&-Troubleshooting
..2025-06-19T09:02:47.940Z pid=56574 tid=15tu INFO: Sidekiq 7.3.9 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>nil}
.................................................................................................................................................................................................
Finished in 0.10617 seconds (files took 0.54088 seconds to load)
195 examples, 0 failures
~/ydah/rspec-sidekiq remove-example
❯ bundle exec rspec
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this …
```
> Change rspec command

- lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb
- spec/rspec/sidekiq/matchers/enqueue_sidekiq_job_spec.rb
- spec/rspec/sidekiq/matchers/have_enqueued_sidekiq_job_spec.rb
Currently
```
expect { 'do nothing' }.to enqueue_sidekiq_job(SomeJob).exactly(0)
```
will result in
```
expected to enqueue 0 SomeJob jobs
with arguments:
-[*(any args)]
but enqueued 0 jobs
```
which I believe is not expected behavior.
> fix matcher to support exactly(0)

- spec/rspec/sidekiq/matchers/be_delayed_spec.rb
Basically, it's better to use the functionality provided by RSpec to represent if branches rather than putting them in RSpec.
> chore: Changing Sidekiq version branching to use RSpec metadata

- spec/rspec/sidekiq/batch_spec.rb
Before:
```
❯ bundle exec rspec
..INFO  2025-09-28T00:45:05.510Z pid=75754 tid=1lp6: Sidekiq 8.0.5 connecting to Redis with options {size: 10, pool_name: "internal", url: nil}
.........................................................................................................................................................................................................
```
After:
```
❯ bundle exec rspec
...........................................................................................................................................................................................................
```
> test: add around block to capture stdout during total method tests
